export const plans = [
  {
    type: 'Free',
    price: 0,
    date: 'per month',
    expiry: 'Free Forever',
    titleFeat: 'Get a bitwarden vault',
    perks: [
      ' Unlimited devices',
      'Passkey management',
      'All the core functions',
      'Always free',
    ],
    limit: 'Share vault items with one other user',
    bttn: 'Get Started today',
  },
  {
    type: 'Premium',
    price: 1,
    date: 'per month',
    expiry: '$10 billed annually',
    titleFeat: 'Enjoy premium features',
    perks: [
      'Bitwarden Authenticator',
      'File attachments',
      'Emergency access',
      'Security reports and more',
    ],
    limit: 'Share vault items with one other user',
    bttn: 'Create Premium Account',
  },
  {
    type: 'Families',
    price: 3.33,
    date: 'per month',
    expiry: 'Up to 6 users, $40 billed annually',
    titleFeat: 'Secure your family logins',
    perks: [
      '6 premium accounts',
      'Unlimited sharing',
      ' Unlimited collections',
      'Organization storage',
    ],
    limit: 'Share vault items between six people',
    bttn: 'Start 7 day free trial',
  },
];
